{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/live_wallpaper\/converter4video"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/live_wallpaper\/converter4video"]}],"sections":[],"abstract":[{"type":"text","text":"Utility class for video processing operations required for Live Photos"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/init(path:)"],"anchor":"Initializers","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/accelerateVideo(at:to:outputPath:completion:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/appendToComposition(_:asset:duration:at:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/cleanTransformVideo(at:outputPath:completion:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/createVideo(from:duration:outputURL:completion:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/durationVideo(at:outputPath:targetDuration:completion:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/getFrame(from:at:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/pixelBuffer(from:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/readAssetIdentifier()","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/resizeVideo(at:outputPath:outputSize:completion:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/rotateVideo(at:outputPath:degree:completion:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/write(dest:assetIdentifier:metaURL:completion:)"],"anchor":"Instance-Methods","generated":true}],"metadata":{"modules":[{"name":"live_Wallpaper"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Converter4Video"}],"title":"Converter4Video","externalID":"c:@M@live_Wallpaper@objc(cs)Converter4Video","roleHeading":"Class","symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Converter4Video"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/objc(pl)NSObject","doc:\/\/com.binarywolf.live-Wallpaper\/s7CVarArgP","doc:\/\/com.binarywolf.live-Wallpaper\/s28CustomDebugStringConvertibleP","doc:\/\/com.binarywolf.live-Wallpaper\/s23CustomStringConvertibleP","doc:\/\/com.binarywolf.live-Wallpaper\/SQ","doc:\/\/com.binarywolf.live-Wallpaper\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Converter4Video"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video"},"references":{"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/resizeVideo(at:outputPath:outputSize:completion:)":{"abstract":[{"type":"text","text":"Resize video to the specified dimensions"}],"navigatorTitle":[{"text":"resizeVideoAt:outputPath:outputSize:completion:","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/resizeVideo(at:outputPath:outputSize:completion:)","title":"resizeVideo(at:outputPath:outputSize:completion:)","url":"\/documentation\/live_wallpaper\/converter4video\/resizevideo(at:outputpath:outputsize:completion:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resizeVideo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outputPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outputSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/appendToComposition(_:asset:duration:at:)":{"url":"\/documentation\/live_wallpaper\/converter4video\/appendtocomposition(_:asset:duration:at:)","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/appendToComposition(_:asset:duration:at:)","role":"symbol","kind":"symbol","title":"appendToComposition(_:asset:duration:at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendToComposition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVMutableCompositionTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVMutableCompositionTrack"},{"text":", ","kind":"text"},{"text":"asset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVAsset","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAsset"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"},{"kind":"text","text":")"}],"abstract":[],"type":"topic"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/rotateVideo(at:outputPath:degree:completion:)":{"url":"\/documentation\/live_wallpaper\/converter4video\/rotatevideo(at:outputpath:degree:completion:)","title":"rotateVideo(at:outputPath:degree:completion:)","type":"topic","role":"symbol","abstract":[{"text":"Rotate video by the specified degree","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rotateVideo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outputPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"degree","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"rotateVideoAt:outputPath:degree:completion:","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/rotateVideo(at:outputPath:degree:completion:)"},"doc://com.binarywolf.live-Wallpaper/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/SQ"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/write(dest:assetIdentifier:metaURL:completion:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeWithDest:assetIdentifier:metaURL:completion:"}],"url":"\/documentation\/live_wallpaper\/converter4video\/write(dest:assetidentifier:metaurl:completion:)","abstract":[{"text":"Process a video and write it with the required Live Photo metadata","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"write"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dest"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"assetIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metaURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"title":"write(dest:assetIdentifier:metaURL:completion:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/write(dest:assetIdentifier:metaURL:completion:)"},"doc://com.binarywolf.live-Wallpaper/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/objc(cs)NSObject"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/createVideo(from:duration:outputURL:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createVideo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"createVideoFrom:duration:outputURL:completion:"}],"url":"\/documentation\/live_wallpaper\/converter4video\/createvideo(from:duration:outputurl:completion:)","type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/createVideo(from:duration:outputURL:completion:)","abstract":[],"title":"createVideo(from:duration:outputURL:completion:)","kind":"symbol","role":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Utility class for video processing operations required for Live Photos"}],"navigatorTitle":[{"text":"Converter4Video","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video","title":"Converter4Video","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Video","kind":"identifier"}],"url":"\/documentation\/live_wallpaper\/converter4video"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/getFrame(from:at:)":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/getFrame(from:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAsset","preciseIdentifier":"c:objc(cs)AVAsset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"title":"getFrame(from:at:)","role":"symbol","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/live_wallpaper\/converter4video\/getframe(from:at:)"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/cleanTransformVideo(at:outputPath:completion:)":{"type":"topic","url":"\/documentation\/live_wallpaper\/converter4video\/cleantransformvideo(at:outputpath:completion:)","navigatorTitle":[{"kind":"identifier","text":"cleanTransformVideoAt:outputPath:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanTransformVideo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"title":"cleanTransformVideo(at:outputPath:completion:)","role":"symbol","abstract":[{"type":"text","text":"Clean up video transform to normalize orientation"}],"kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/cleanTransformVideo(at:outputPath:completion:)"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/pixelBuffer(from:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pixelBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":") -> ","kind":"text"},{"text":"CVPixelBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/pixelBuffer(from:)","kind":"symbol","abstract":[],"title":"pixelBuffer(from:)","role":"symbol","url":"\/documentation\/live_wallpaper\/converter4video\/pixelbuffer(from:)"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"},"doc://com.binarywolf.live-Wallpaper/SH":{"type":"unresolvable","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/SH","title":"Swift.Hashable"},"doc://com.binarywolf.live-Wallpaper/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/objc(pl)NSObject"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/durationVideo(at:outputPath:targetDuration:completion:)":{"navigatorTitle":[{"text":"durationVideoAt:outputPath:targetDuration:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"durationVideo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outputPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"targetDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/live_wallpaper\/converter4video\/durationvideo(at:outputpath:targetduration:completion:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/durationVideo(at:outputPath:targetDuration:completion:)","title":"durationVideo(at:outputPath:targetDuration:completion:)","abstract":[{"type":"text","text":"Adjust video duration to match the target duration"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/init(path:)":{"title":"init(path:)","url":"\/documentation\/live_wallpaper\/converter4video\/init(path:)","kind":"symbol","navigatorTitle":[{"text":"initWithPath:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/init(path:)","abstract":[{"text":"Initialize with a file path","type":"text"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"path","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/readAssetIdentifier()":{"abstract":[{"type":"text","text":"Read the asset identifier from the video’s metadata"}],"title":"readAssetIdentifier()","url":"\/documentation\/live_wallpaper\/converter4video\/readassetidentifier()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"readAssetIdentifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/readAssetIdentifier()","navigatorTitle":[{"kind":"identifier","text":"readAssetIdentifier"}],"type":"topic"},"doc://com.binarywolf.live-Wallpaper/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.binarywolf.live-Wallpaper/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/s28CustomDebugStringConvertibleP"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/accelerateVideo(at:to:outputPath:completion:)":{"abstract":[{"text":"Modify video speed to match the required duration","type":"text"}],"title":"accelerateVideo(at:to:outputPath:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accelerateVideo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime","text":"CMTime"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/accelerateVideo(at:to:outputPath:completion:)","kind":"symbol","url":"\/documentation\/live_wallpaper\/converter4video\/acceleratevideo(at:to:outputpath:completion:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accelerateVideoAt:to:outputPath:completion:"}]},"doc://com.binarywolf.live-Wallpaper/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"Converter4Video","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Converter4Video"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Converter4Video"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/accelerateVideo(at:to:outputPath:completion:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/cleanTransformVideo(at:outputPath:completion:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/createVideo(from:duration:outputURL:completion:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/durationVideo(at:outputPath:targetDuration:completion:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/init(path:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/readAssetIdentifier()","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/resizeVideo(at:outputPath:outputSize:completion:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/rotateVideo(at:outputPath:degree:completion:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/write(dest:assetIdentifier:metaURL:completion:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Video","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1resizeVideo(at:outputPath:outputSize:completion:)\/title","op":"replace","value":"resizeVideoAt:outputPath:outputSize:completion:"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1resizeVideo(at:outputPath:outputSize:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"resizeVideoAt:outputPath:outputSize:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1rotateVideo(at:outputPath:degree:completion:)\/title","op":"replace","value":"rotateVideoAt:outputPath:degree:completion:"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1rotateVideo(at:outputPath:degree:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rotateVideoAt:outputPath:degree:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1write(dest:assetIdentifier:metaURL:completion:)\/title","op":"replace","value":"writeWithDest:assetIdentifier:metaURL:completion:"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1write(dest:assetIdentifier:metaURL:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"writeWithDest:assetIdentifier:metaURL:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1createVideo(from:duration:outputURL:completion:)\/title","op":"replace","value":"createVideoFrom:duration:outputURL:completion:"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1createVideo(from:duration:outputURL:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createVideoFrom:duration:outputURL:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/title","op":"replace","value":"Converter4Video"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/fragments","op":"replace","value":[{"kind":"identifier","text":"Converter4Video"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/navigatorTitle","op":"replace","value":[{"text":"Converter4Video","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1cleanTransformVideo(at:outputPath:completion:)\/title","op":"replace","value":"cleanTransformVideoAt:outputPath:completion:"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1cleanTransformVideo(at:outputPath:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cleanTransformVideoAt:outputPath:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1durationVideo(at:outputPath:targetDuration:completion:)\/title","op":"replace","value":"durationVideoAt:outputPath:targetDuration:completion:"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1durationVideo(at:outputPath:targetDuration:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"durationVideoAt:outputPath:targetDuration:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1init(path:)\/title","op":"replace","value":"initWithPath:"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1init(path:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPath:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1readAssetIdentifier()\/title","op":"replace","value":"readAssetIdentifier"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1readAssetIdentifier()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"readAssetIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1accelerateVideo(at:to:outputPath:completion:)\/title","op":"replace","value":"accelerateVideoAt:to:outputPath:completion:"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1accelerateVideo(at:to:outputPath:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"accelerateVideoAt:to:outputPath:completion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}