{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Utility class to handle image conversion for Live Photos"},{"type":"text","text":" "},{"type":"text","text":"Handles adding the necessary metadata to images to work as part of a Live Photo pair"}],"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/init(image:)"],"anchor":"Initializers"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/read()","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/write(dest:assetIdentifier:)"],"anchor":"Instance-Methods"}],"metadata":{"roleHeading":"Class","title":"Converter4Image","externalID":"c:@M@live_Wallpaper@objc(cs)Converter4Image","navigatorTitle":[{"kind":"identifier","text":"Converter4Image"}],"symbolKind":"class","role":"symbol","modules":[{"name":"live_Wallpaper"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Converter4Image"}]},"variants":[{"paths":["\/documentation\/live_wallpaper\/converter4image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/live_wallpaper\/converter4image"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Converter4Image"}],"languages":["swift"]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/objc(pl)NSObject","doc:\/\/com.binarywolf.live-Wallpaper\/s7CVarArgP","doc:\/\/com.binarywolf.live-Wallpaper\/s28CustomDebugStringConvertibleP","doc:\/\/com.binarywolf.live-Wallpaper\/s23CustomStringConvertibleP","doc:\/\/com.binarywolf.live-Wallpaper\/SQ","doc:\/\/com.binarywolf.live-Wallpaper\/SH"]}],"references":{"doc://com.binarywolf.live-Wallpaper/SQ":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.binarywolf.live-Wallpaper/SH":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.binarywolf.live-Wallpaper/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.binarywolf.live-Wallpaper/objc(cs)NSObject":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.binarywolf.live-Wallpaper/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Image/read()":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"read","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/read()","title":"read()","url":"\/documentation\/live_wallpaper\/converter4image\/read()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"Read the asset identifier from an image’s metadata","type":"text"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Image/write(dest:assetIdentifier:)":{"url":"\/documentation\/live_wallpaper\/converter4image\/write(dest:assetidentifier:)","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/write(dest:assetIdentifier:)","navigatorTitle":[{"kind":"identifier","text":"writeWithDest:assetIdentifier:"}],"abstract":[{"text":"Write the image to disk with the required Live Photo metadata","type":"text"}],"title":"write(dest:assetIdentifier:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dest","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"assetIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Image/init(image:)":{"abstract":[{"text":"Initialize with a UIImage","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImage:"}],"url":"\/documentation\/live_wallpaper\/converter4image\/init(image:)","title":"init(image:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/init(image:)","role":"symbol","kind":"symbol"},"doc://com.binarywolf.live-Wallpaper/objc(pl)NSObject":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.binarywolf.live-Wallpaper/s7CVarArgP":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Image":{"title":"Converter4Image","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Image","kind":"identifier"}],"navigatorTitle":[{"text":"Converter4Image","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image","kind":"symbol","abstract":[{"text":"Utility class to handle image conversion for Live Photos","type":"text"},{"text":" ","type":"text"},{"text":"Handles adding the necessary metadata to images to work as part of a Live Photo pair","type":"text"}],"url":"\/documentation\/live_wallpaper\/converter4image"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"Converter4Image","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"Converter4Image","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"Converter4Image","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/init(image:)","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/read()","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/write(dest:assetIdentifier:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Image","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image~1read()\/title","value":"read","op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image~1read()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"read","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image~1write(dest:assetIdentifier:)\/title","value":"writeWithDest:assetIdentifier:","op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image~1write(dest:assetIdentifier:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"writeWithDest:assetIdentifier:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image~1init(image:)\/title","value":"initWithImage:","op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image~1init(image:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithImage:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/title","value":"Converter4Image","op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/fragments","value":[{"kind":"identifier","text":"Converter4Image"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/navigatorTitle","value":[{"kind":"identifier","text":"Converter4Image"}],"op":"replace"}]}]}