{"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/objc(pl)NSObject","doc:\/\/com.binarywolf.live-Wallpaper\/s7CVarArgP","doc:\/\/com.binarywolf.live-Wallpaper\/s28CustomDebugStringConvertibleP","doc:\/\/com.binarywolf.live-Wallpaper\/s23CustomStringConvertibleP","doc:\/\/com.binarywolf.live-Wallpaper\/SQ","doc:\/\/com.binarywolf.live-Wallpaper\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/LivePhotoUtil\/convertVideo(_:complete:)"],"title":"Type Methods","anchor":"Type-Methods","generated":true}],"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"LivePhotoUtil","kind":"identifier"}],"externalID":"c:objc(cs)LivePhotoUtil","role":"symbol","title":"LivePhotoUtil","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LivePhotoUtil","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"live_Wallpaper"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivePhotoUtil","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/live_wallpaper\/livephotoutil"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/live_wallpaper\/livephotoutil"]}],"hierarchy":{"paths":[["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper"]]},"identifier":{"url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/LivePhotoUtil","interfaceLanguage":"swift"},"references":{"doc://com.binarywolf.live-Wallpaper/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/objc(pl)NSObject","type":"unresolvable"},"doc://com.binarywolf.live-Wallpaper/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/SH","type":"unresolvable"},"doc://com.binarywolf.live-Wallpaper/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/s7CVarArgP","type":"unresolvable"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/LivePhotoUtil/convertVideo(_:complete:)":{"navigatorTitle":[{"kind":"identifier","text":"convertVideo:complete:"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/LivePhotoUtil\/convertVideo(_:complete:)","kind":"symbol","role":"symbol","url":"\/documentation\/live_wallpaper\/livephotoutil\/convertvideo(_:complete:)","type":"topic","abstract":[],"title":"convertVideo(_:complete:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertVideo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"complete"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")!)"}]},"doc://com.binarywolf.live-Wallpaper/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"},"doc://com.binarywolf.live-Wallpaper/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/objc(cs)NSObject","type":"unresolvable"},"doc://com.binarywolf.live-Wallpaper/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/SQ","type":"unresolvable"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/LivePhotoUtil":{"type":"topic","url":"\/documentation\/live_wallpaper\/livephotoutil","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivePhotoUtil","kind":"identifier"}],"navigatorTitle":[{"text":"LivePhotoUtil","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/LivePhotoUtil","abstract":[],"title":"LivePhotoUtil","kind":"symbol"},"doc://com.binarywolf.live-Wallpaper/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"LivePhotoUtil","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"LivePhotoUtil"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"LivePhotoUtil"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/LivePhotoUtil\/convertVideo(_:complete:)"],"anchor":"Type-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"LivePhotoUtil"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"convertVideo:complete:","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1LivePhotoUtil~1convertVideo(_:complete:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"convertVideo:complete:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1LivePhotoUtil~1convertVideo(_:complete:)\/fragments","op":"replace"},{"value":"LivePhotoUtil","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1LivePhotoUtil\/title","op":"replace"},{"value":[{"text":"LivePhotoUtil","kind":"identifier"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1LivePhotoUtil\/fragments","op":"replace"},{"value":[{"text":"LivePhotoUtil","kind":"identifier"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1LivePhotoUtil\/navigatorTitle","op":"replace"}]}]}