{"metadata":{"symbolKind":"module","title":"live_Wallpaper","role":"collection","roleHeading":"Application","externalID":"live_Wallpaper","modules":[{"name":"live_Wallpaper"}]},"sections":[],"variants":[{"paths":["\/documentation\/live_wallpaper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/live_wallpaper"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[[]]},"topicSections":[{"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/LivePhotoCreator","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/LivePhotoUtil","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoProcessor","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/WallpaperViewModel"],"title":"Classes","anchor":"Classes","generated":true},{"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/AnimatedScaleEffect","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/AppIconView","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/AspectRatioWarningView","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/BackgroundGradient","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/BenefitRow","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/BenefitsSection","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/BottomActionBar","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/CallToActionSection","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/ContentCardStyle","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/ContentView","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/ErrorAlertButtons","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/ErrorAlertMessage","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/FeatureRow","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/FeaturesSection","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/HeaderSection","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/HeroSection","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/LoadingOverlay","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/NavigationMenu","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/PrimaryButtonStyle","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/RangeSlider","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/SpeedControlComponent","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/SpeedOptionComponent","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/SpeedRecommendationView","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/SuccessAlertButtons","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/SuccessAlertMessage","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/TimeFormatter","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/TipSectionComponent","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/TipsCallToAction","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/TipsView","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoEditingView","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoFile","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoPicker","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoPickerSheet","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoPlayerComponent","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoProcessingActions","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoSelectionInterface","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoSelectionView","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoTrimmingComponent","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/live_WallpaperApp"],"title":"Structures","anchor":"Structures","generated":true},{"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoProcessingError"],"title":"Enumerations","anchor":"Enumerations","generated":true},{"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/AVFoundation","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/SwiftUICore","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/UIKit"],"title":"Extended Modules","anchor":"Extended-Modules","generated":true}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper"},"references":{"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/VideoProcessingError":{"role":"symbol","url":"\/documentation\/live_wallpaper\/videoprocessingerror","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoProcessingError","kind":"symbol","abstract":[{"type":"text","text":"Enumeration of possible errors during video processing"}],"type":"topic","title":"VideoProcessingError","navigatorTitle":[{"text":"VideoProcessingError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoProcessingError","kind":"identifier"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/VideoTrimmingComponent":{"type":"topic","title":"VideoTrimmingComponent","url":"\/documentation\/live_wallpaper\/videotrimmingcomponent","abstract":[{"type":"text","text":"Component for video trimming controls and time selection"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoTrimmingComponent"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoTrimmingComponent","navigatorTitle":[{"kind":"identifier","text":"VideoTrimmingComponent"}],"role":"symbol","kind":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/ErrorAlertButtons":{"type":"topic","url":"\/documentation\/live_wallpaper\/erroralertbuttons","kind":"symbol","abstract":[{"text":"Action buttons for error alert dialogs.","type":"text"}],"navigatorTitle":[{"text":"ErrorAlertButtons","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/ErrorAlertButtons","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorAlertButtons","kind":"identifier"}],"title":"ErrorAlertButtons"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/VideoProcessingActions":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoProcessingActions","navigatorTitle":[{"text":"VideoProcessingActions","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/live_wallpaper\/videoprocessingactions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoProcessingActions","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Component for video processing actions and status"}],"title":"VideoProcessingActions","type":"topic"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/VideoFile":{"role":"symbol","type":"topic","url":"\/documentation\/live_wallpaper\/videofile","abstract":[{"type":"text","text":"A transferable implementation for video files in the Live Wallpaper Creator app."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFile","kind":"identifier"}],"navigatorTitle":[{"text":"VideoFile","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoFile","kind":"symbol","title":"VideoFile"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/RangeSlider":{"abstract":[{"text":"A custom SwiftUI range slider for selecting a time range within a video","type":"text"},{"text":" ","type":"text"},{"text":"Features smooth animations, drag gestures, and enforces a maximum range constraint","type":"text"}],"role":"symbol","url":"\/documentation\/live_wallpaper\/rangeslider","title":"RangeSlider","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/RangeSlider","type":"topic","navigatorTitle":[{"text":"RangeSlider","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RangeSlider","kind":"identifier"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/ErrorAlertMessage":{"role":"symbol","abstract":[{"text":"Message content for error alert dialogs.","type":"text"}],"kind":"symbol","url":"\/documentation\/live_wallpaper\/erroralertmessage","navigatorTitle":[{"kind":"identifier","text":"ErrorAlertMessage"}],"title":"ErrorAlertMessage","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/ErrorAlertMessage","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorAlertMessage"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/SpeedOptionComponent":{"url":"\/documentation\/live_wallpaper\/speedoptioncomponent","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/SpeedOptionComponent","title":"SpeedOptionComponent","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpeedOptionComponent"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SpeedOptionComponent"}],"type":"topic"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/BackgroundGradient":{"kind":"symbol","url":"\/documentation\/live_wallpaper\/backgroundgradient","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BackgroundGradient","kind":"identifier"}],"navigatorTitle":[{"text":"BackgroundGradient","kind":"identifier"}],"title":"BackgroundGradient","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/BackgroundGradient","role":"symbol","type":"topic","abstract":[]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/PrimaryButtonStyle":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/PrimaryButtonStyle","kind":"symbol","title":"PrimaryButtonStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrimaryButtonStyle"}],"navigatorTitle":[{"kind":"identifier","text":"PrimaryButtonStyle"}],"abstract":[{"type":"text","text":"A view modifier for primary button styling with state management."}],"type":"topic","url":"\/documentation\/live_wallpaper\/primarybuttonstyle","role":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/ContentView":{"title":"ContentView","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContentView","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/ContentView","type":"topic","url":"\/documentation\/live_wallpaper\/contentview","navigatorTitle":[{"text":"ContentView","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Main content view for the Live Wallpaper Creator app.","type":"text"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/AppIconView":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/AppIconView","type":"topic","abstract":[{"text":"A custom app icon view that displays an animated app icon","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"AppIconView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AppIconView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/live_wallpaper\/appiconview","title":"AppIconView"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/VideoPickerSheet":{"title":"VideoPickerSheet","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPickerSheet","kind":"identifier"}],"navigatorTitle":[{"text":"VideoPickerSheet","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/live_wallpaper\/videopickersheet","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoPickerSheet","abstract":[],"role":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/SuccessAlertMessage":{"title":"SuccessAlertMessage","kind":"symbol","type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/SuccessAlertMessage","navigatorTitle":[{"text":"SuccessAlertMessage","kind":"identifier"}],"url":"\/documentation\/live_wallpaper\/successalertmessage","abstract":[{"text":"Message content for success alert dialogs.","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SuccessAlertMessage","kind":"identifier"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/HeaderSection":{"role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeaderSection"}],"url":"\/documentation\/live_wallpaper\/headersection","navigatorTitle":[{"kind":"identifier","text":"HeaderSection"}],"title":"HeaderSection","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/HeaderSection"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/BenefitRow":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BenefitRow","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/BenefitRow","abstract":[],"url":"\/documentation\/live_wallpaper\/benefitrow","type":"topic","title":"BenefitRow","navigatorTitle":[{"text":"BenefitRow","kind":"identifier"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/SpeedControlComponent":{"title":"SpeedControlComponent","abstract":[{"type":"text","text":"Component for speed control selection and feedback"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/SpeedControlComponent","role":"symbol","navigatorTitle":[{"text":"SpeedControlComponent","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpeedControlComponent","kind":"identifier"}],"url":"\/documentation\/live_wallpaper\/speedcontrolcomponent","type":"topic","kind":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/VideoPlayerComponent":{"url":"\/documentation\/live_wallpaper\/videoplayercomponent","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayerComponent","kind":"identifier"}],"navigatorTitle":[{"text":"VideoPlayerComponent","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"VideoPlayerComponent","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoPlayerComponent","abstract":[{"type":"text","text":"Component for displaying and controlling video playback"}],"type":"topic"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/VideoSelectionView":{"url":"\/documentation\/live_wallpaper\/videoselectionview","abstract":[{"type":"text","text":"View for selecting a video from the user’s photo library."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoSelectionView"}],"title":"VideoSelectionView","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoSelectionView","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoSelectionView"}],"type":"topic"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/CallToActionSection":{"abstract":[],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/CallToActionSection","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallToActionSection","kind":"identifier"}],"navigatorTitle":[{"text":"CallToActionSection","kind":"identifier"}],"title":"CallToActionSection","type":"topic","kind":"symbol","url":"\/documentation\/live_wallpaper\/calltoactionsection","role":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/LoadingOverlay":{"role":"symbol","navigatorTitle":[{"text":"LoadingOverlay","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/LoadingOverlay","type":"topic","title":"LoadingOverlay","url":"\/documentation\/live_wallpaper\/loadingoverlay","kind":"symbol","abstract":[{"text":"A simple fullscreen loading overlay","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoadingOverlay","kind":"identifier"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/AnimatedScaleEffect":{"title":"AnimatedScaleEffect","url":"\/documentation\/live_wallpaper\/animatedscaleeffect","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AnimatedScaleEffect"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/AnimatedScaleEffect","kind":"symbol","abstract":[{"text":"A view modifier that adds gentle scale animation effects.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedScaleEffect"}],"type":"topic"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/SpeedRecommendationView":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/SpeedRecommendationView","navigatorTitle":[{"text":"SpeedRecommendationView","kind":"identifier"}],"type":"topic","url":"\/documentation\/live_wallpaper\/speedrecommendationview","abstract":[{"type":"text","text":"A view that provides speed recommendations based on video content type"}],"title":"SpeedRecommendationView","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpeedRecommendationView","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/TipSectionComponent":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/TipSectionComponent","navigatorTitle":[{"text":"TipSectionComponent","kind":"identifier"}],"abstract":[{"type":"text","text":"A reusable component for displaying individual tips and advice sections."}],"kind":"symbol","title":"TipSectionComponent","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TipSectionComponent","kind":"identifier"}],"role":"symbol","url":"\/documentation\/live_wallpaper\/tipsectioncomponent"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/VideoSelectionInterface":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoSelectionInterface","type":"topic","abstract":[],"role":"symbol","kind":"symbol","title":"VideoSelectionInterface","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoSelectionInterface","kind":"identifier"}],"url":"\/documentation\/live_wallpaper\/videoselectioninterface","navigatorTitle":[{"text":"VideoSelectionInterface","kind":"identifier"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/BenefitsSection":{"title":"BenefitsSection","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"BenefitsSection","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/BenefitsSection","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BenefitsSection","kind":"identifier"}],"url":"\/documentation\/live_wallpaper\/benefitssection"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/AspectRatioWarningView":{"kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/AspectRatioWarningView","type":"topic","abstract":[],"title":"AspectRatioWarningView","url":"\/documentation\/live_wallpaper\/aspectratiowarningview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AspectRatioWarningView"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AspectRatioWarningView","kind":"identifier"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/LivePhotoCreator":{"title":"LivePhotoCreator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivePhotoCreator","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"LivePhotoCreator","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Utility class for creating Live Photos from video files"}],"url":"\/documentation\/live_wallpaper\/livephotocreator","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/LivePhotoCreator"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/TimeFormatter":{"type":"topic","url":"\/documentation\/live_wallpaper\/timeformatter","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimeFormatter","kind":"identifier"}],"navigatorTitle":[{"text":"TimeFormatter","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/TimeFormatter","abstract":[{"type":"text","text":"Utility struct for formatting time values for display"}],"title":"TimeFormatter","kind":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/FeaturesSection":{"title":"FeaturesSection","url":"\/documentation\/live_wallpaper\/featuressection","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/FeaturesSection","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeaturesSection","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"FeaturesSection","kind":"identifier"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/UIKit":{"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/live_wallpaper\/uikit","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/UIKit","role":"collection","title":"UIKit"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/TipsView":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TipsView"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A view that displays helpful tips and best practices for creating Live Wallpapers"}],"url":"\/documentation\/live_wallpaper\/tipsview","title":"TipsView","role":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/TipsView","navigatorTitle":[{"kind":"identifier","text":"TipsView"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/SuccessAlertButtons":{"kind":"symbol","url":"\/documentation\/live_wallpaper\/successalertbuttons","navigatorTitle":[{"text":"SuccessAlertButtons","kind":"identifier"}],"title":"SuccessAlertButtons","abstract":[{"text":"Action buttons for success alert dialogs.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/SuccessAlertButtons","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SuccessAlertButtons","kind":"identifier"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/HeroSection":{"type":"topic","url":"\/documentation\/live_wallpaper\/herosection","abstract":[{"text":"An animated hero section component for the video selection interface.","type":"text"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/HeroSection","navigatorTitle":[{"kind":"identifier","text":"HeroSection"}],"title":"HeroSection","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeroSection"}],"role":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/LivePhotoUtil":{"type":"topic","url":"\/documentation\/live_wallpaper\/livephotoutil","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivePhotoUtil","kind":"identifier"}],"navigatorTitle":[{"text":"LivePhotoUtil","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/LivePhotoUtil","abstract":[],"title":"LivePhotoUtil","kind":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/SwiftUICore":{"title":"SwiftUICore","abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/SwiftUICore","url":"\/documentation\/live_wallpaper\/swiftuicore"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Utility class for video processing operations required for Live Photos"}],"navigatorTitle":[{"text":"Converter4Video","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video","title":"Converter4Video","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Video","kind":"identifier"}],"url":"\/documentation\/live_wallpaper\/converter4video"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/VideoProcessor":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoProcessor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoProcessor","kind":"identifier"}],"title":"VideoProcessor","type":"topic","abstract":[{"type":"text","text":"Utility class for video processing operations"}],"kind":"symbol","url":"\/documentation\/live_wallpaper\/videoprocessor","role":"symbol","navigatorTitle":[{"text":"VideoProcessor","kind":"identifier"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/FeatureRow":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeatureRow","kind":"identifier"}],"role":"symbol","title":"FeatureRow","type":"topic","url":"\/documentation\/live_wallpaper\/featurerow","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/FeatureRow","navigatorTitle":[{"kind":"identifier","text":"FeatureRow"}],"abstract":[{"text":"A reusable component for displaying individual app features.","type":"text"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/VideoPicker":{"abstract":[{"text":"UIViewControllerRepresentable wrapper for UIImagePickerController","type":"text"},{"text":" ","type":"text"},{"text":"Provides a native video picker interface for selecting videos","type":"text"}],"url":"\/documentation\/live_wallpaper\/videopicker","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoPicker","navigatorTitle":[{"text":"VideoPicker","kind":"identifier"}],"title":"VideoPicker","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPicker","kind":"identifier"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/live_WallpaperApp":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/live_WallpaperApp","url":"\/documentation\/live_wallpaper\/live_wallpaperapp","title":"live_WallpaperApp","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"live_WallpaperApp","kind":"identifier"}],"abstract":[{"text":"The main app structure for Live Wallpaper Creator.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"live_WallpaperApp","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/AVFoundation":{"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/AVFoundation","url":"\/documentation\/live_wallpaper\/avfoundation","abstract":[],"role":"collection","title":"AVFoundation","type":"topic","kind":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/BottomActionBar":{"title":"BottomActionBar","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BottomActionBar","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/BottomActionBar","type":"topic","url":"\/documentation\/live_wallpaper\/bottomactionbar","navigatorTitle":[{"text":"BottomActionBar","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/ContentCardStyle":{"type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/ContentCardStyle","title":"ContentCardStyle","abstract":[{"type":"text","text":"A view modifier that applies consistent card-style formatting."}],"url":"\/documentation\/live_wallpaper\/contentcardstyle","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ContentCardStyle","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContentCardStyle","kind":"identifier"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/NavigationMenu":{"title":"NavigationMenu","kind":"symbol","url":"\/documentation\/live_wallpaper\/navigationmenu","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NavigationMenu"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationMenu"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/NavigationMenu","abstract":[{"type":"text","text":"A reusable navigation menu component for the app’s toolbar."}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/TipsCallToAction":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TipsCallToAction"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TipsCallToAction"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/TipsCallToAction","url":"\/documentation\/live_wallpaper\/tipscalltoaction","title":"TipsCallToAction","abstract":[]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Image":{"title":"Converter4Image","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Image","kind":"identifier"}],"navigatorTitle":[{"text":"Converter4Image","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image","kind":"symbol","abstract":[{"text":"Utility class to handle image conversion for Live Photos","type":"text"},{"text":" ","type":"text"},{"text":"Handles adding the necessary metadata to images to work as part of a Live Photo pair","type":"text"}],"url":"\/documentation\/live_wallpaper\/converter4image"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/VideoEditingView":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoEditingView"}],"type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/VideoEditingView","abstract":[{"type":"text","text":"View for trimming and previewing a selected video for Live Wallpaper creation."}],"url":"\/documentation\/live_wallpaper\/videoeditingview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoEditingView"}],"title":"VideoEditingView"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/WallpaperViewModel":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WallpaperViewModel"}],"url":"\/documentation\/live_wallpaper\/wallpaperviewmodel","type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/WallpaperViewModel","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"WallpaperViewModel"}],"abstract":[{"text":"ViewModel responsible for handling video selection, processing, and saving as Live Photos.","type":"text"}],"title":"WallpaperViewModel"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"title":"Classes","generated":true,"identifiers":["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/LivePhotoUtil"],"anchor":"Classes"}]},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1LivePhotoUtil\/title","op":"replace","value":"LivePhotoUtil"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1LivePhotoUtil\/fragments","op":"replace","value":[{"kind":"identifier","text":"LivePhotoUtil"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1LivePhotoUtil\/navigatorTitle","op":"replace","value":[{"text":"LivePhotoUtil","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/title","op":"replace","value":"Converter4Video"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/fragments","op":"replace","value":[{"text":"Converter4Video","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/navigatorTitle","op":"replace","value":[{"text":"Converter4Video","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/title","op":"replace","value":"Converter4Image"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/fragments","op":"replace","value":[{"kind":"identifier","text":"Converter4Image"}]},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Converter4Image"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}