{"variants":[{"paths":["\/documentation\/live_wallpaper\/converter4video\/appendtocomposition(_:asset:duration:at:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/appendToComposition(_:asset:duration:at:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendToComposition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"compositionTrack","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AVMutableCompositionTrack","preciseIdentifier":"c:objc(cs)AVMutableCompositionTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"asset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVAsset","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAsset"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMTime","kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime"},{"text":", ","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMTime","kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video"]]},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Method","title":"appendToComposition(_:asset:duration:at:)","externalID":"s:14live_Wallpaper15Converter4VideoC19appendToComposition_5asset8duration2atySo09AVMutableG5TrackC_So7AVAssetCSo6CMTimeaAMtF","modules":[{"name":"live_Wallpaper"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendToComposition"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVMutableCompositionTrack","kind":"typeIdentifier","text":"AVMutableCompositionTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"asset"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAsset","kind":"typeIdentifier","text":"AVAsset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/appendToComposition(_:asset:duration:at:)":{"url":"\/documentation\/live_wallpaper\/converter4video\/appendtocomposition(_:asset:duration:at:)","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/appendToComposition(_:asset:duration:at:)","role":"symbol","kind":"symbol","title":"appendToComposition(_:asset:duration:at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendToComposition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVMutableCompositionTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVMutableCompositionTrack"},{"text":", ","kind":"text"},{"text":"asset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVAsset","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAsset"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"},{"kind":"text","text":")"}],"abstract":[],"type":"topic"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Utility class for video processing operations required for Live Photos"}],"navigatorTitle":[{"text":"Converter4Video","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video","title":"Converter4Video","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Video","kind":"identifier"}],"url":"\/documentation\/live_wallpaper\/converter4video"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Converter4Video","op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/title"},{"value":[{"text":"Converter4Video","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/fragments"},{"value":[{"kind":"identifier","text":"Converter4Video"}],"op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/navigatorTitle"}]}]}