{"identifier":{"url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/cleanTransformVideo(at:outputPath:completion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/live_wallpaper\/converter4video\/cleantransformvideo(at:outputpath:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/live_wallpaper\/converter4video\/cleantransformvideo(at:outputpath:completion:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanTransformVideo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inputPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"inputPath","content":[{"inlineContent":[{"type":"text","text":"Path to the input video"}],"type":"paragraph"}]},{"name":"outputPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Path for the processed output video"}]}]},{"name":"completion","content":[{"inlineContent":[{"text":"Completion handler with success status and optional error","type":"text"}],"type":"paragraph"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cleanTransformVideo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputPath"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"title":"cleanTransformVideo(at:outputPath:completion:)","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@live_Wallpaper@objc(cs)Converter4Video(im)cleanTransformVideoAt:outputPath:completion:","navigatorTitle":[{"kind":"identifier","text":"cleanTransformVideoAt:outputPath:completion:"}],"modules":[{"name":"live_Wallpaper"}],"symbolKind":"method"},"sections":[],"abstract":[{"type":"text","text":"Clean up video transform to normalize orientation"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video"]]},"references":{"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/cleanTransformVideo(at:outputPath:completion:)":{"type":"topic","url":"\/documentation\/live_wallpaper\/converter4video\/cleantransformvideo(at:outputpath:completion:)","navigatorTitle":[{"kind":"identifier","text":"cleanTransformVideoAt:outputPath:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanTransformVideo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"title":"cleanTransformVideo(at:outputPath:completion:)","role":"symbol","abstract":[{"type":"text","text":"Clean up video transform to normalize orientation"}],"kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/cleanTransformVideo(at:outputPath:completion:)"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Utility class for video processing operations required for Live Photos"}],"navigatorTitle":[{"text":"Converter4Video","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video","title":"Converter4Video","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Video","kind":"identifier"}],"url":"\/documentation\/live_wallpaper\/converter4video"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"cleanTransformVideoAt:outputPath:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cleanTransformVideoAt:outputPath:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cleanTransformVideoAt:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"inputPath","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outputPath:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"outputPath","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"Path to the input video","type":"text"}],"type":"paragraph"}],"name":"inputPath"},{"content":[{"inlineContent":[{"type":"text","text":"Path for the processed output video"}],"type":"paragraph"}],"name":"outputPath"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Completion handler with success status and optional error","type":"text"}]}],"name":"completion"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"cleanTransformVideoAt:outputPath:completion:","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1cleanTransformVideo(at:outputPath:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cleanTransformVideoAt:outputPath:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1cleanTransformVideo(at:outputPath:completion:)\/fragments"},{"op":"replace","value":"Converter4Video","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/title"},{"op":"replace","value":[{"text":"Converter4Video","kind":"identifier"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Converter4Video"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/navigatorTitle"}]}]}