{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/live_wallpaper\/converter4video\/durationvideo(at:outputpath:targetduration:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/live_wallpaper\/converter4video\/durationvideo(at:outputpath:targetduration:completion:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video"]]},"metadata":{"navigatorTitle":[{"text":"durationVideoAt:outputPath:targetDuration:completion:","kind":"identifier"}],"modules":[{"name":"live_Wallpaper"}],"symbolKind":"method","title":"durationVideo(at:outputPath:targetDuration:completion:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"durationVideo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"outputPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"targetDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"externalID":"c:@M@live_Wallpaper@objc(cs)Converter4Video(im)durationVideoAt:outputPath:targetDuration:completion:","role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/durationVideo(at:outputPath:targetDuration:completion:)"},"abstract":[{"text":"Adjust video duration to match the target duration","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"durationVideo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"inputPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"outputPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"targetDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"inputPath","content":[{"inlineContent":[{"type":"text","text":"Path to the input video"}],"type":"paragraph"}]},{"name":"outputPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Path for the processed output video"}]}]},{"name":"targetDuration","content":[{"type":"paragraph","inlineContent":[{"text":"Target duration in seconds","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Completion handler with success status and optional error"}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/durationVideo(at:outputPath:targetDuration:completion:)":{"navigatorTitle":[{"text":"durationVideoAt:outputPath:targetDuration:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"durationVideo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outputPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"targetDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/live_wallpaper\/converter4video\/durationvideo(at:outputpath:targetduration:completion:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/durationVideo(at:outputPath:targetDuration:completion:)","title":"durationVideo(at:outputPath:targetDuration:completion:)","abstract":[{"type":"text","text":"Adjust video duration to match the target duration"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Utility class for video processing operations required for Live Photos"}],"navigatorTitle":[{"text":"Converter4Video","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video","title":"Converter4Video","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Video","kind":"identifier"}],"url":"\/documentation\/live_wallpaper\/converter4video"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"durationVideoAt:outputPath:targetDuration:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"durationVideoAt:outputPath:targetDuration:completion:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"durationVideoAt:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"inputPath"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"outputPath"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetDuration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"targetDuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Path to the input video"}]}],"name":"inputPath"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Path for the processed output video"}]}],"name":"outputPath"},{"content":[{"inlineContent":[{"type":"text","text":"Target duration in seconds"}],"type":"paragraph"}],"name":"targetDuration"},{"content":[{"inlineContent":[{"type":"text","text":"Completion handler with success status and optional error"}],"type":"paragraph"}],"name":"completion"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1durationVideo(at:outputPath:targetDuration:completion:)\/title","value":"durationVideoAt:outputPath:targetDuration:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1durationVideo(at:outputPath:targetDuration:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"durationVideoAt:outputPath:targetDuration:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/title","value":"Converter4Video","op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/fragments","value":[{"text":"Converter4Video","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/navigatorTitle","value":[{"text":"Converter4Video","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}