{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pixelBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/live_wallpaper\/converter4video\/pixelbuffer(from:)"]}],"hierarchy":{"paths":[["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pixelBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"s:14live_Wallpaper15Converter4VideoC11pixelBuffer4fromSo11CVBufferRefaSgSo7UIImageC_tF","roleHeading":"Instance Method","title":"pixelBuffer(from:)","modules":[{"name":"live_Wallpaper"}],"symbolKind":"method","role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/pixelBuffer(from:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Utility class for video processing operations required for Live Photos"}],"navigatorTitle":[{"text":"Converter4Video","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video","title":"Converter4Video","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Video","kind":"identifier"}],"url":"\/documentation\/live_wallpaper\/converter4video"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/pixelBuffer(from:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pixelBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":") -> ","kind":"text"},{"text":"CVPixelBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/pixelBuffer(from:)","kind":"symbol","abstract":[],"title":"pixelBuffer(from:)","role":"symbol","url":"\/documentation\/live_wallpaper\/converter4video\/pixelbuffer(from:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/title","value":"Converter4Video"},{"op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/fragments","value":[{"text":"Converter4Video","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/navigatorTitle","value":[{"text":"Converter4Video","kind":"identifier"}]}]}]}