{"hierarchy":{"paths":[["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/readAssetIdentifier()"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"readAssetIdentifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Asset identifier string if found, nil otherwise"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/live_wallpaper\/converter4video\/readassetidentifier()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/live_wallpaper\/converter4video\/readassetidentifier()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Read the asset identifier from the video’s metadata","type":"text"}],"sections":[],"kind":"symbol","metadata":{"title":"readAssetIdentifier()","modules":[{"name":"live_Wallpaper"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"readAssetIdentifier","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"readAssetIdentifier","kind":"identifier"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@live_Wallpaper@objc(cs)Converter4Video(im)readAssetIdentifier"},"references":{"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Utility class for video processing operations required for Live Photos"}],"navigatorTitle":[{"text":"Converter4Video","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video","title":"Converter4Video","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Video","kind":"identifier"}],"url":"\/documentation\/live_wallpaper\/converter4video"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/readAssetIdentifier()":{"abstract":[{"type":"text","text":"Read the asset identifier from the video’s metadata"}],"title":"readAssetIdentifier()","url":"\/documentation\/live_wallpaper\/converter4video\/readassetidentifier()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"readAssetIdentifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/readAssetIdentifier()","navigatorTitle":[{"kind":"identifier","text":"readAssetIdentifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"readAssetIdentifier"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"readAssetIdentifier","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"readAssetIdentifier","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"Asset identifier string if found, nil otherwise"}],"type":"paragraph"}]}},{"op":"replace","value":"Converter4Video","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/title"},{"op":"replace","value":[{"text":"Converter4Video","kind":"identifier"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/fragments"},{"op":"replace","value":[{"text":"Converter4Video","kind":"identifier"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/navigatorTitle"},{"op":"replace","value":"readAssetIdentifier","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1readAssetIdentifier()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"readAssetIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1readAssetIdentifier()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}