{"metadata":{"externalID":"c:@M@live_Wallpaper@objc(cs)Converter4Video(im)writeWithDest:assetIdentifier:metaURL:completion:","title":"write(dest:assetIdentifier:metaURL:completion:)","modules":[{"name":"live_Wallpaper"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dest","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"assetIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"metaURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"writeWithDest:assetIdentifier:metaURL:completion:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/live_wallpaper\/converter4video\/write(dest:assetidentifier:metaurl:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/live_wallpaper\/converter4video\/write(dest:assetidentifier:metaurl:completion:)"]}],"sections":[],"abstract":[{"text":"Process a video and write it with the required Live Photo metadata","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dest","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"assetIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"metaURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"dest","content":[{"inlineContent":[{"text":"Destination path for the output file","type":"text"}],"type":"paragraph"}]},{"name":"assetIdentifier","content":[{"inlineContent":[{"type":"text","text":"Asset identifier to associate with this video"}],"type":"paragraph"}]},{"name":"metaURL","content":[{"inlineContent":[{"text":"URL to a metadata source file","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion handler with success status and optional error"}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/write(dest:assetIdentifier:metaURL:completion:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video/write(dest:assetIdentifier:metaURL:completion:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeWithDest:assetIdentifier:metaURL:completion:"}],"url":"\/documentation\/live_wallpaper\/converter4video\/write(dest:assetidentifier:metaurl:completion:)","abstract":[{"text":"Process a video and write it with the required Live Photo metadata","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"write"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dest"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"assetIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metaURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"title":"write(dest:assetIdentifier:metaURL:completion:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video\/write(dest:assetIdentifier:metaURL:completion:)"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Video":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Utility class for video processing operations required for Live Photos"}],"navigatorTitle":[{"text":"Converter4Video","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Video","title":"Converter4Video","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Video","kind":"identifier"}],"url":"\/documentation\/live_wallpaper\/converter4video"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"writeWithDest:assetIdentifier:metaURL:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"writeWithDest:assetIdentifier:metaURL:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"writeWithDest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dest"},{"kind":"text","text":" "},{"kind":"identifier","text":"assetIdentifier:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"assetIdentifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"metaURL:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"metaURL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Destination path for the output file","type":"text"}]}],"name":"dest"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Asset identifier to associate with this video"}]}],"name":"assetIdentifier"},{"content":[{"inlineContent":[{"text":"URL to a metadata source file","type":"text"}],"type":"paragraph"}],"name":"metaURL"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Completion handler with success status and optional error","type":"text"}]}],"name":"completion"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"writeWithDest:assetIdentifier:metaURL:completion:","op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1write(dest:assetIdentifier:metaURL:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeWithDest:assetIdentifier:metaURL:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video~1write(dest:assetIdentifier:metaURL:completion:)\/fragments"},{"value":"Converter4Video","op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/title"},{"value":[{"kind":"identifier","text":"Converter4Video"}],"op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/fragments"},{"value":[{"kind":"identifier","text":"Converter4Video"}],"op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Video\/navigatorTitle"}]}]}