{"variants":[{"paths":["\/documentation\/live_wallpaper\/converter4image\/init(image:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/live_wallpaper\/converter4image\/init(image:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Initializer","modules":[{"name":"live_Wallpaper"}],"symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"initWithImage:","kind":"identifier"}],"externalID":"c:@M@live_Wallpaper@objc(cs)Converter4Image(im)initWithImage:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":")","kind":"text"}],"title":"init(image:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/init(image:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The source image to be processed"}],"type":"paragraph"}],"name":"image"}]}],"kind":"symbol","abstract":[{"text":"Initialize with a UIImage","type":"text"}],"references":{"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Image/init(image:)":{"abstract":[{"text":"Initialize with a UIImage","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImage:"}],"url":"\/documentation\/live_wallpaper\/converter4image\/init(image:)","title":"init(image:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/init(image:)","role":"symbol","kind":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Image":{"title":"Converter4Image","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Image","kind":"identifier"}],"navigatorTitle":[{"text":"Converter4Image","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image","kind":"symbol","abstract":[{"text":"Utility class to handle image conversion for Live Photos","type":"text"},{"text":" ","type":"text"},{"text":"Handles adding the necessary metadata to images to work as part of a Live Photo pair","type":"text"}],"url":"\/documentation\/live_wallpaper\/converter4image"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithImage:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithImage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The source image to be processed"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"initWithImage:","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image~1init(image:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image~1init(image:)\/fragments","op":"replace"},{"value":"Converter4Image","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/title","op":"replace"},{"value":[{"text":"Converter4Image","kind":"identifier"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Converter4Image"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/navigatorTitle","op":"replace"}]}]}