{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"The asset identifier string if found, nil otherwise"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/live_wallpaper\/converter4image\/read()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/live_wallpaper\/converter4image\/read()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Read the asset identifier from an image’s metadata"}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@live_Wallpaper@objc(cs)Converter4Image(im)read","title":"read()","navigatorTitle":[{"kind":"identifier","text":"read"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","modules":[{"name":"live_Wallpaper"}]},"identifier":{"url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/read()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Image/read()":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"read","kind":"identifier"}],"identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/read()","title":"read()","url":"\/documentation\/live_wallpaper\/converter4image\/read()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"Read the asset identifier from an image’s metadata","type":"text"}]},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Image":{"title":"Converter4Image","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Image","kind":"identifier"}],"navigatorTitle":[{"text":"Converter4Image","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image","kind":"symbol","abstract":[{"text":"Utility class to handle image conversion for Live Photos","type":"text"},{"text":" ","type":"text"},{"text":"Handles adding the necessary metadata to images to work as part of a Live Photo pair","type":"text"}],"url":"\/documentation\/live_wallpaper\/converter4image"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"read","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"read"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"read"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The asset identifier string if found, nil otherwise"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"read","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image~1read()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"read"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image~1read()\/fragments","op":"replace"},{"value":"Converter4Image","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Converter4Image"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Converter4Image"}],"path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}