{"abstract":[{"text":"Write the image to disk with the required Live Photo metadata","type":"text"}],"identifier":{"url":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/write(dest:assetIdentifier:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/live_wallpaper\/converter4image\/write(dest:assetidentifier:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/live_wallpaper\/converter4image\/write(dest:assetidentifier:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dest","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"assetIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"dest","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The destination file path where the image will be saved"}]}]},{"name":"assetIdentifier","content":[{"inlineContent":[{"type":"text","text":"The asset identifier to associate with this image"}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"metadata":{"role":"symbol","title":"write(dest:assetIdentifier:)","symbolKind":"method","externalID":"c:@M@live_Wallpaper@objc(cs)Converter4Image(im)writeWithDest:assetIdentifier:","modules":[{"name":"live_Wallpaper"}],"navigatorTitle":[{"text":"writeWithDest:assetIdentifier:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dest","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"assetIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image"]]},"kind":"symbol","references":{"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Image/write(dest:assetIdentifier:)":{"url":"\/documentation\/live_wallpaper\/converter4image\/write(dest:assetidentifier:)","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image\/write(dest:assetIdentifier:)","navigatorTitle":[{"kind":"identifier","text":"writeWithDest:assetIdentifier:"}],"abstract":[{"text":"Write the image to disk with the required Live Photo metadata","type":"text"}],"title":"write(dest:assetIdentifier:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dest","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"assetIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper/Converter4Image":{"title":"Converter4Image","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Converter4Image","kind":"identifier"}],"navigatorTitle":[{"text":"Converter4Image","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper\/Converter4Image","kind":"symbol","abstract":[{"text":"Utility class to handle image conversion for Live Photos","type":"text"},{"text":" ","type":"text"},{"text":"Handles adding the necessary metadata to images to work as part of a Live Photo pair","type":"text"}],"url":"\/documentation\/live_wallpaper\/converter4image"},"doc://com.binarywolf.live-Wallpaper/documentation/live_Wallpaper":{"title":"live_Wallpaper","url":"\/documentation\/live_wallpaper","kind":"symbol","identifier":"doc:\/\/com.binarywolf.live-Wallpaper\/documentation\/live_Wallpaper","abstract":[],"type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"writeWithDest:assetIdentifier:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeWithDest:assetIdentifier:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"writeWithDest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dest"},{"kind":"text","text":" "},{"kind":"identifier","text":"assetIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"assetIdentifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"dest","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The destination file path where the image will be saved"}]}]},{"name":"assetIdentifier","content":[{"inlineContent":[{"text":"The asset identifier to associate with this image","type":"text"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"writeWithDest:assetIdentifier:","op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image~1write(dest:assetIdentifier:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeWithDest:assetIdentifier:"}],"op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image~1write(dest:assetIdentifier:)\/fragments"},{"value":"Converter4Image","op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/title"},{"value":[{"kind":"identifier","text":"Converter4Image"}],"op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/fragments"},{"value":[{"kind":"identifier","text":"Converter4Image"}],"op":"replace","path":"\/references\/doc:~1~1com.binarywolf.live-Wallpaper~1documentation~1live_Wallpaper~1Converter4Image\/navigatorTitle"}]}]}